version: '3'
services:
  postgres:
    image: postgres:9.5.4
    volumes:
      - pgsql-data:/var/lib/postgresql/data
  app:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/railsapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  pgsql-data:
